// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zakbysosovmfztpstwzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpha2J5c29zb3ZtZnp0cHN0d3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjY1NzAsImV4cCI6MjA2NjQ0MjU3MH0.3a28ofo49Ybn0B_2mdI5q7yFOx9XbrB7nWBdJn1z7xM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);